export type YouthProfile = {
  slot: number;
  name: string;
  department: string;
  role: string;
  image: string;
  imageLayout: "landscape" | "portrait";
  imagePosition: string;
  intro: string;
  reflection: string;
  keyword: string;
  pending?: boolean;
};

export const youthProfiles: YouthProfile[] = [
  {
    slot: 1,
    name: "郭丽莎",
    department: "益阳市高新区支行",
    role: "助理综合客户经理",
    image: "/people/01-guolisha.webp",
    imageLayout: "portrait",
    imagePosition: "50% 52%",
    intro: "大家好，我是郭丽莎，喜欢做手工和唱歌。现在在中国银行益阳市高新区支行担任助理综合客户经理。",
    reflection: "工作中我始终坚守金融行业规章制度，拒绝宴请、礼品及利益回扣，不利用职务之便谋取私利。对待贷款审批、客户授信秉持公平公正原则，依规办事。我会以自律约束言行，守住职业红线，用心服务客户的同时恪守廉洁准则，踏实做好本职工作。",
    keyword: "公平公正",
  },
  {
    slot: 2,
    name: "欧阳龙旺",
    department: "资阳支行",
    role: "助理综合服务经理",
    image: "/people/02-ouyanglongwang.webp",
    imageLayout: "portrait",
    imagePosition: "50% 48%",
    intro: "我是资阳支行助理综合服务经理欧阳龙旺，喜欢阅读，性格沉稳。",
    reflection: "入行三年让我对廉洁有了新的认识。我日常负责客户业务办理与厅堂秩序维护。立足本职，我始终坚守廉洁从业底线：对待客户秉公服务，办理业务严守规章流程。常怀敬畏之心，筑牢思想防线，以清正作风履职尽责，用真诚合规服务客户，彰显青年银行从业者的责任与操守。",
    keyword: "心存敬畏",
  },
  {
    slot: 3,
    name: "吴希雅",
    department: "沅江支行营业部",
    role: "助理综合服务经理",
    image: "/people/03-wuxiya.webp",
    imageLayout: "portrait",
    imagePosition: "50% 48%",
    intro: "大家好，我是吴希雅，是沅江支行营业部的一名助理综合服务经理。",
    reflection: "入行三年，在日常工作中，我深刻认识到廉政风险潜藏于小事小节。我将时刻绷紧廉洁自律这根弦，严守党纪行规，破除“小节无碍”思想，坚持按制度流程办事，不为人情变通原则，自觉抵制各类利益诱惑，划清公私界限，主动接受各方监督，把廉洁从业落实到每一项服务保障工作中，做到知敬畏、守底线，干净履职尽责。",
    keyword: "守住底线",
  },
  {
    slot: 4,
    name: "唐婉琴",
    department: "南县兴盛路支行",
    role: "助理综合服务经理",
    image: "/people/04-tangwanqin.webp",
    imageLayout: "portrait",
    imagePosition: "50% 42%",
    intro: "大家好，我是唐婉琴，现就职于南县兴盛路支行，是一名助理综合服务经理。",
    reflection: "作为一线助理综合服务经理，守好窗口就是守住廉洁防线。严守制度、不越红线，不利用岗位便利谋私利，依规办理每一笔业务，清白做人、干净做事。",
    keyword: "干净做事",
  },
  {
    slot: 5,
    name: "余晶晶",
    department: "益阳市桥北支行",
    role: "助理综合服务经理",
    image: "/people/05-yujingjing.webp",
    imageLayout: "portrait",
    imagePosition: "50% 52%",
    intro: "大家好，我是余晶晶，目前就职于中国银行益阳市桥北支行，是一名助理综合服务经理。",
    reflection: "坚守金融初心，严守纪律底线，依规履职，清白做人，永葆银行从业者廉洁本色。",
    keyword: "廉洁本色",
  },
  {
    slot: 6,
    name: "黄欣",
    department: "龙洲北路支行",
    role: "助理综合服务经理",
    image: "/people/06-huangxin.webp",
    imageLayout: "portrait",
    imagePosition: "50% 38%",
    intro: "大家好，我是来自龙洲北路支行的黄欣，目前是一名助理综合服务经理。",
    reflection: "综合服务岗位平凡，每天重复存取款、转账、开卡，每笔业务都有章可循。也恰恰是这份平凡让我明白：廉洁更多时候是一种日常选择——是面对“通融一下”时能否说出“按制度办”，是无人注意时是否依然核对清每一笔账目。古人讲“慎独”，廉洁不为做给别人看，只为对得起经手的每一件事。能力可以慢慢学，底线一次也不能破。愿以此自勉，踏实、清白、心安。",
    keyword: "慎独",
  },
  {
    slot: 7,
    name: "文慧",
    department: "桃江县劳动支行",
    role: "助理个人客户经理",
    image: "/people/07-wenhui.webp",
    imageLayout: "portrait",
    imagePosition: "50% 50%",
    intro: "大家好，我是文慧，来自中国银行桃江县劳动支行，现在是一名助理个人客户经理。",
    reflection: "作为2023年加入中国银行的青年员工，我深知“廉洁”二字重若千钧。它不仅是百年中行的红色基因，更是我们职业生涯的“第一粒扣子”。面对经手的每一笔数字，我将时刻心怀敬畏，严守规章，让合规成为肌肉记忆。身处金融一线，从柜员到客户经理，岗位在变，初心不改，我愿以清正为帆，自觉抵制诱惑，在服务客户时保持纯粹初心。廉洁不是束缚，而是保护，是对客户血汗钱的尊重，更是对自己和家人最大的负责。我将脚踏实地，让青春在风清气正的岗位上干净绽放。",
    keyword: "清正初心",
  },
  {
    slot: 8,
    name: "付梦雅",
    department: "益阳市迎宾路支行",
    role: "助理综合服务经理",
    image: "/people/08-fumengya.webp",
    imageLayout: "portrait",
    imagePosition: "50% 45%",
    intro: "大家好，我是付梦雅，现就职于益阳市迎宾路支行，是一名助理综合服务经理。自入行以来，我立足本职、脚踏实地，钻研业务技能，提升自身业务能力与职业素养。",
    reflection: "清廉立身，笃行致远。日常工作中，我时刻坚守职业道德，严格规范业务操作，严守金融纪律，坚守初心，以廉洁实干诠释青年担当。",
    keyword: "廉洁实干",
  },
  {
    slot: 9,
    name: "夏清怡",
    department: "桃江县劳动支行",
    role: "助理综合服务经理",
    image: "/people/09-xiaqingyi.webp",
    imageLayout: "portrait",
    imagePosition: "50% 40%",
    intro: "大家好，我是夏清怡，现工作于桃江县劳动支行，是一名助理综合服务经理。",
    reflection: "作为银行青年员工，我始终将廉洁自律融入日常工作。严格遵守行内合规制度，规范业务操作，坚守职业底线，不越红线、不碰高压线；对待客户公平公正、真诚服务，自觉抵制不良风气，以初心立足岗位，以自律护航职业生涯，筑牢金融从业者的清廉思想防线。",
    keyword: "廉洁自律",
  },
  {
    slot: 10,
    name: "邹欣妍",
    department: "益阳市龙洲北路支行",
    role: "助理综合客户经理",
    image: "/people/10-zhouxinyan.webp",
    imageLayout: "landscape",
    imagePosition: "50% 50%",
    intro: "大家好，我是邹欣妍，现工作于益阳市龙洲北路支行。",
    reflection: "作为银行青年员工，我视廉洁为职业第一准则。日常工作中严守规章制度，规范操作每一笔业务，对客户一视同仁、真诚服务，坚决抵制利益诱惑。以清正之心履职，以自律之行致远，筑牢基层金融一线的廉洁防线。",
    keyword: "清正自律",
  },
];
